apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-api
  namespace: events-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: events-api
  template:
    metadata:
      labels:
        app: events-api
    spec:
      containers:
        - name: events-api
          image: events-api:local
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /api/v1/events
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/events
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: events-api-svc
  namespace: events-api
spec:
  selector:
    app: events-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
