apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: events-api-ingress
  namespace: events-api
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: events-api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: events-api-svc
                port:
                  number: 80
